cp-zookeeper:
  servers: 1
  persistence:
    enabled: false

cp-kafka:
  brokers: 1
  persistence:
    enabled: false
  configurationOverrides:
    "offsets.topic.replication.factor": "1"
    "default.replication.factor": "1"
    "min.insync.replicas": "1"

cp-kafka-connect:
  enabled: false

cp-ksql-server:
  enabled: false
